name: final
services:
  postgres:
    image: postgres:latest
    container_name: pg
    environment:
      POSTGRES_DB: "taxi"
      POSTGRES_USER: "peter"
      POSTGRES_PASSWORD: "peter"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      #- ./input_data:/docker-entrypoint-initdb.d
      - ./input_data:/input_data
      - ./output_data_pg:/output_data_pg
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U peter -d taxi"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
volumes:
  pg_data: